export const RECEIVE_SWIPERS = 'receive_swipers'  //接收轮播图
export const RECEIVE_ADDRESS = 'receive_address'  //接收地址信息
export const RECEIVE_FOODCATEGORY = 'receive_foodcategory'  //接收食品分类列表
export const RECEIVE_SHOPLIST = 'receive_shoplist' //接收商家列表
export const RECEIVE_USERINFO = 'receive_userinfo'  //接收用户信息
export const RECEIVE_LOGOUT = 'receive_logout'  //接收用户登出
export const RECEIVE_SHOPINFO = 'receive_shopinfo'  //接受商家信息
export const RECEIVE_SHOPGOODS = 'receive_shopgoods'  //接受商家食物
export const RECEIVE_SHOPRATINGS = 'receive_shopratings'  //接受商家评价
export const INCREMENT_FOOD_COUNT = 'increment_food_count'  //增加食物数量
export const DECREMENT_FOOD_COUNT = 'decrement_food_count'  //减少食物数量
export const CLEAR_MYCART = 'clear_mycart'  //清空购物车
export const RECEIVE_SEARCH_SHOPS = 'receive_search_shops' // 接收搜索的商家数组